apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uidam-authorization-server.fullname" . }}
  labels: {{- include "uidam-authorization-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "uidam-authorization-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config-tenants: {{ include (print $.Template.BasePath "/configmap-tenants-config.yaml") . | sha256sum }}
        checksum/config-default: {{ include (print $.Template.BasePath "/configmap-default-configurations.yaml") . | sha256sum }}
      labels: {{- include "uidam-authorization-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "uidam-authorization-server.fullname" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "{{ .Values.metrics.basePath }}/health/liveness"
            port: {{ .Values.metrics.prometheus.agent.port }}     
            scheme: HTTP   
          initialDelaySeconds: 30    
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3  
        readinessProbe:
          httpGet:
            path: "{{ .Values.metrics.basePath }}/health/readiness"
            port: {{ .Values.metrics.prometheus.agent.port }}
            scheme: HTTP
          initialDelaySeconds: 30    
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3            
        envFrom:
        - configMapRef:
            name: {{ include "uidam-authorization-server.fullname" . }}
        {{- range $tenantKey, $tenantConfig := .Values.multiTenant.tenants }}
        {{- if ne $tenantKey "default" }}
        {{- if or (contains $tenantKey $.Values.multiTenant.tenantIds) (eq $tenantKey $.Values.multiTenant.defaultTenant) }}
        - configMapRef:
            name: {{ include "uidam-authorization-server.fullname" $ }}-tenant-{{ $tenantKey }}
        {{- end }}
        {{- end }}
        {{- end }}
        - configMapRef:
            name: {{ include "uidam-authorization-server.fullname" . }}-tenant-default
        volumeMounts:
          - name: uidam-jks
            mountPath: /etc/uidam/keystore
          - name: app-keys
            mountPath: /etc/uidam/cert
        resources: {{- toYaml .Values.resources | nindent 10 }}
        env:
          - name: LOGLEVEL
            value: {{ .Values.logging.logLevel | quote }}
          - name: POSTGRESQL_HOST
            value: "{{ .Values.postgresql.host }}"
          - name: POSTGRESQL_PORT
            value: "{{ .Values.postgresql.port }}"
          # Global secrets from main secret
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.postgresql.secretName }}"
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.postgresql.secretName }}"
                key: password
          - name: KEYSTORE_PASS
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.postgresql.secretName }}"
                key: keystorePassword

          {{- $defaultSecretName := printf "%s-tenant-default-credentials" (include "uidam-authorization-server.fullname" .) }}
          # DEFAULT tenant secrets (tenant-default.properties placeholders)
          - name: DEFAULT_POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: username
          - name: DEFAULT_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: password
          - name: DEFAULT_KEYSTORE_PASS
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: keystorePassword
          - name: DEFAULT_TENANT_CLIENT_SECRET_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: clientsecretkey
          - name: DEFAULT_TENANT_CLIENT_SECRET_ENCRYPTION_SALT
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: clientsecretsalt
          - name: DEFAULT_TENANT_CAPTCHA_RECAPTCHA_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: ignite.recaptcha.key.secret
          - name: DEFAULT_MFA_SECRET_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: mfaSecretEncryptionKey
          - name: DEFAULT_MFA_SECRET_ENCRYPTION_SALT
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: mfaSecretEncryptionSalt
          {{- range $index, $client := .Values.multiTenant.tenants.default.externalIdpRegisteredClients }}
          - name: DEFAULT_EXTERNAL_IDP_REGISTERED_CLIENT_LIST_{{ $index }}_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ $defaultSecretName }}
                key: {{ printf "%sIDPSecret" (lower $client.clientName) }}
          {{- end }}
          {{- range $tenantKey, $tenantConfig := .Values.multiTenant.tenants }}
          {{- if ne $tenantKey "default" }}
          {{- if or (contains $tenantKey $.Values.multiTenant.tenantIds) (eq $tenantKey $.Values.multiTenant.defaultTenant) }}
          {{- $tenantSecretName := printf "%s-tenant-%s-credentials" (include "uidam-authorization-server.fullname" $) $tenantKey }}
          # {{ $tenantKey | upper }} tenant secrets
          - name: tenants_profile_{{ $tenantKey }}_user-name
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: username
          - name: tenants_profile_{{ $tenantKey }}_password
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: password
          - name: tenants_profile_{{ $tenantKey }}_key-store_key-store-password
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: keystorePassword
          - name: tenants_profile_{{ $tenantKey }}_client_secret-encryption-key
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: clientsecretkey
          - name: tenants_profile_{{ $tenantKey }}_client_secret-encryption-salt
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: clientsecretsalt
          - name: tenants_profile_{{ $tenantKey }}_captcha_recaptcha-key-secret
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: ignite.recaptcha.key.secret
          - name: tenants_profile_{{ $tenantKey }}_mfa-secret-encryption-key
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: mfaSecretEncryptionKey
          - name: tenants_profile_{{ $tenantKey }}_mfa-secret-encryption-salt
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: mfaSecretEncryptionSalt
          {{- range $index, $client := $tenantConfig.externalIdpRegisteredClients }}
          - name: tenants_profile_{{ $tenantKey }}_external-idp-registered-client-list[{{ $index }}]_client-secret
            valueFrom:
              secretKeyRef:
                name: {{ $tenantSecretName }}
                key: {{ printf "%sIDPSecret" (lower $client.clientName) }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: uidam-jks
          configMap:
            name: {{ include "uidam-authorization-server.fullname" . }}-jks
        - name: app-keys
          configMap:
            name: {{ include "uidam-authorization-server.fullname" . }}-app

