apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uidam-authorization-server.fullname" . }}-tenant-default-credentials
  labels: {{- include "uidam-authorization-server.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgresql.userName | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
  keystorePassword: {{ .Values.tenantSecrets.default.keystorePassword | b64enc | quote }}
  ignite.recaptcha.key.secret: {{ .Values.tenantSecrets.default.igniteRecaptchaKeySecret | b64enc | quote }}
  clientsecretkey: {{ .Values.tenantSecrets.default.clientsecretkey | b64enc | quote }}
  clientsecretsalt: {{ .Values.tenantSecrets.default.clientsecretsalt | b64enc | quote }}
  clientSecret: {{ .Values.tenantSecrets.default.clientSecret | b64enc | quote }}
# Updated to match latest opensource-perf-app structure and logic for tenant default secret, all secrets set to 'ChangeMe'
