apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uidam-authorization-server.fullname" . }}-credentials
  labels: {{- include "uidam-authorization-server.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgresql.userName | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
  keystorePassword: {{ .Values.secrets.keystorePassword | b64enc | quote }}


